-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d')
FROM REST_REVIEW A INNER JOIN (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(*) DESC LIMIT 1) B ON A.MEMBER_ID = B.MEMBER_ID LEFT JOIN MEMBER_PROFILE C ON A.MEMBER_ID = C.MEMBER_ID
ORDER BY A.REVIEW_DATE, A.REVIEW_TEXT