-- 코드를 작성해주세요
WITH BASE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, ID, SIZE_OF_COLONY, MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) AS YEAR_MAX
    FROM ECOLI_DATA
)
SELECT YEAR, (YEAR_MAX - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM BASE
ORDER BY YEAR, YEAR_DEV;